tasks:
  - name: terraform
    before: |     #if init, when workspace close it will not init again
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli
    command: cd $GITPOD_REPO_ROOT
    
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode    
    - hashicorp.terraform
    - hediet.vscode-drawio
    - vscode-icons-team.vscode-icons
    - ms-azuretools.vscode-docker
    - redhat.ansible
    - streetsidesoftware.code-spell-checker
    - tabnine.tabnine-vscode
