version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      #- ./uptime-kuma-data:/app/data
      - /home/admtech/docker_volumes/uptime-kuma/data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    environment:
      TZ: 'Asia/Hong_Kong'
    restart: unless-stopped
    networks:
      uptime-kuma:

networks:
  uptime-kuma:
    external: false
    name: uptime-kuma